### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by lancecarlson**
I just tested this locally with {deep: true} and it worked flawlessly. I didn't run the test however.

### CODE REVIEW

**Comment by ajoslin** [comment]
Thanks for the PR.

However, I think this is probably out of scope of this library. I would suggest making a separate `pascalcase-keys-deep`.

**Comment by sramam** [comment]
@ajoslin, given https://github.com/sindresorhus/camelcase-keys/commit/94195701442b3ab257d17596a689780656a172ec, any change of heart?

**Comment by tomiiide** [comment]
I think this will be a great improvement to the library.

**Comment by ajoslin** [comment]
If someone wants to open a new PR without the quick-lru dependency (which is a bad idea IMO) I will merge it

**Pull request closed without merging**
